name: pulse
favicon: null
layout_spectrum: 0.5702117898035794
typography_spectrum: 0.7046253518201411
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9777458268217742
  lightness: 0.2939568131696433
  saturation: 0.7974280752241611
  rhythmicContrast: 0.5512243749108166
purpose: []
